window.languageMap = {
    "装箱单": "Packing List",
    "入库": "Storage",
    "当前": "current",
    "共": "common",
    "该拣货车已有绑定的出库单": "The picking cart already has a bound outbound order",
    "完成": "Finish",
    "返回出货单": "back to shipper",
    "请求失败": "Request failed",
    "切换库位": "switch location",
    "撤销入库": "Undo storage",
    "用户登录": "User login",
    "必填": "required",
    "下载测试": "download test",
    "字段类型错误,应该为": "The field type is wrong, it should be",
    "找不到组件！": "Component not found!",
    "暂无可用出库单": "No delivery order available",
    "sku不存在,请核实后再打印": "sku does not exist, please verify before printing",
    "fnsku不存在,请核实后再打印": "fnsku does not exist, please verify before printing",
    "打印": "Print",
    "搜索": "search",
    "退出登录": "sign out",
    "文件类型错误: 请上传Excel文件": "File type error: Please upload an Excel file",
    "文件类型错误: 请上传图片或pdf文件": "File type error: Please upload an image or pdf file",
    "请选择库位": "Please select a location",
    "打印出库单": "Print out the inventory list",
    "确定": "Sure",
    "校验接口不存在，请检查": "The verification interface does not exist, please check",
    "上传图片": "upload image",
    "出库单": "Outbound order",
    "关闭": "closure",
    "总件数已超过货箱数量": "The total number of pieces has exceeded the number of boxes",
    "保存成功": "Saved successfully",
    "打印库位标签": "Print Location Labels",
    "请输入": "please enter",
    "提交成功！": "Submitted successfully!",
    "确定要": "sure to",
    "请选择需要操作的数据": "Please select the data to be operated",
    "添加分库位": "Add sub-location",
    "共有": "in total",
    "请选择操作数据": "Please select operation data",
    "身份已经过期": "status has expired",
    "去登录": "to log in",
    "返回主页": "return to home page"
};