window.languageMap = {
    "装箱单": "Lista de embalaje",
    "入库": "Almacenamiento",
    "当前": "actual",
    "共": "común",
    "该拣货车已有绑定的出库单": "El carrito de selección ya tiene un pedido de salida enlazado",
    "完成": "Finalizar",
    "返回出货单": "volver al remitente",
    "请求失败": "Solicitud fallida",
    "切换库位": "cambiar de ubicación",
    "撤销入库": "Deshacer almacenamiento",
    "用户登录": "Inicio de sesión de usuario",
    "必填": "requerido",
    "下载测试": "descargar prueba",
    "字段类型错误,应该为": "El tipo de campo es incorrecto, debería ser",
    "找不到组件！": "¡Componente no encontrado!",
    "暂无可用出库单": "No hay orden de entrega disponible",
    "sku不存在,请核实后再打印": "sku no existe, verifique antes de imprimir",
    "fnsku不存在,请核实后再打印": "fnsku no existe, verifique antes de imprimir",
    "打印": "Imprimir",
    "搜索": "buscar",
    "退出登录": "desconectar",
    "文件类型错误: 请上传Excel文件": "Error de tipo de archivo: cargue un archivo de Excel",
    "文件类型错误: 请上传图片或pdf文件": "Error de tipo de archivo: cargue una imagen o un archivo pdf",
    "请选择库位": "Selecciona una ubicación",
    "打印出库单": "Imprime la lista de inventario",
    "确定": "Seguro",
    "校验接口不存在，请检查": "La interfaz de verificación no existe, verifique",
    "上传图片": "cargar imagen",
    "出库单": "Orden de salida",
    "关闭": "cierre",
    "总件数已超过货箱数量": "El número total de piezas ha superado el número de cajas.",
    "保存成功": "Guardado exitosamente",
    "打印库位标签": "Imprimir etiquetas de ubicación",
    "请输入": "por favor escribe",
    "提交成功！": "¡Enviado satisfactoriamente!",
    "确定要": "seguro de",
    "请选择需要操作的数据": "Por favor seleccione los datos a operar",
    "添加分库位": "Añadir sububicación",
    "共有": "en total",
    "请选择操作数据": "Seleccione los datos de la operación",
    "身份已经过期": "el estado ha caducado",
    "去登录": "iniciar sesión",
    "返回主页": "regresar a la página principal"
};